language:
- php
- c

php:
- 5.3
- 5.4
- 5.5
- 5.6

before_script:
- sudo apt-get update
- sudo apt-get install apache2 php5-dev libpcre3-dev gcc make git
- git clone https://github.com/smceframework2/zephir
- cd zephir
- phpize -v
- ./install-json
- ./install -c
- zephir init Smce
- mv ../zep smce
- cd smce
- zephir build



notifications:
  email: false
